baseURL: https://coollibs.github.io/CoolLab-Devlog/
languageCode: en-us
defaultContentLanguage: en
title: Cool Lab
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: cool-lab
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: A patchwork of creative tools based on [Cool](https://github.com/CoolLibs).
  homeMetaContent: A patchwork of creative tools based on Cool.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: false
  logoAlt: "An alternative text description of the logo"

menu:
  nav:
    - name: Home
      url: /
      weight: 1
      
    - name: Blog
      url: /post/
      weight: 2
      
    - name: Our Philosophy
      url: /our-philosophy/
      weight: 3

    - name: Our Roadmap
      url: /our-roadmap/
      weight: 4
            
    - name: Our Coding Guidelines
      url: /our-coding-guidelines/
      weight: 5

    - name: About
      url: /about/
      weight: 6
      
    - name: Tags
      url: /tags/
      weight: 7
    - name: RSS
      url: /index.xml
      weight: 8

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2